name: Build and deploy Node.js app to Azure Web App - sampleapp

on:
  push:
      branches:
      - master
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          rm -rf node_modules
          npm i -f

      - name: Zip all files for upload between jobs
        run: zip --symlinks -r nest.zip ./* .env
              
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: nest.zip

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'eshopx'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5C47275CF58044CE9BC7D9A58A3E2807 }}
          package: nest.zip

      - name: Delete zip file
        run: rm nest.zip
